name: horilla_mobile
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  quickalert: ^1.1.0
  odoo_rpc: ^0.5.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  animated_notch_bottom_bar: ^1.0.0
  flutter_svg: ^2.0.10+1
  contained_tab_bar_view: ^0.8.0
  date_format_field: ^0.1.0

  # UPDATED VERSION TO SUPPORT intl 0.20.x
  date_field: ^6.0.3+1

  flutter_rounded_date_picker: ^3.0.4
  table_calendar: ^3.1.1
  shimmer: ^3.0.0
  convex_bottom_bar: ^3.2.0
  multiselect_dropdown_flutter: ^0.0.7
  flutter_pdfview: ^1.3.2
  image_picker: ^1.1.1
  device_info_plus: ^10.1.0
  file_picker: ^8.0.3
  permission_handler: ^11.3.1
  dio: ^5.4.3+1
  salomon_bottom_bar: ^3.3.2
  cool_alert: ^2.0.1
  timeline_tile: ^2.0.0
  flutter_typeahead: ^4.0.0
  url_launcher: ^6.3.0
  fl_chart: ^0.68.0
  open_file: ^3.3.2
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  flutter_local_notifications: ^17.2.1+2
  timeago: ^3.7.0
  web_socket_channel: ^3.0.1
  connectivity: ^3.0.6
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.0.3
  loading_animation_widget: ^1.2.1
  flutter_ringtone_player: ^4.0.0+3
  flutter_html: ^3.0.0-beta.2
  webview_flutter: ^4.8.0

  # UPDATED VERSION TO SUPPORT intl 0.20.2
  flutter_quill: ^11.0.0

  animated_bottom_navigation_bar: ^1.3.3

dependency_overrides:
  flutter_keyboard_visibility: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/
